name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: push docker images to docker hub
    runs-on: ubuntu-latest
    environment: main

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push UI docker image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64, linux/arm64
          context: docker/ui/
          file: docker/ui/Dockerfile
          push: true
          tags: |
            jfvopensource/plutonia-ui:latest

      - name: Build and push API docker image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64, linux/arm64
          context: docker/api/
          file: docker/api/Dockerfile
          push: true
          tags: |
            jfvopensource/plutonia-api:latest
